# Generated by Django 2.0.2 on 2018-02-16 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('compania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example.Company')),
            ],
        ),
    ]
